root: true
extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - prettier
env:
  node: true
rules:
  'import/prefer-default-export': 0
  'import/no-unresolved': 0
  'global-require': 0
